[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#222224"
foreground = "#E2DBCC"

[colors.cursor]
cursor = "#A2A1A5"

[colors.normal]
black   = "#4D4D50"
red     = "#202659"
green   = "#2A3577"
yellow  = "#87315E"
blue    = "#823690"
magenta = "#A73735"
cyan    = "#A17E33"
white   = "#E2DBCC"

[colors.bright]
black   = "#9E998E"
red     = "#232A63"
green   = "#313D8B"
yellow  = "#973569"
blue    = "#973EA7"
magenta = "#D84643"
cyan    = "#D6A844"
white   = "#E2DBCC"