[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#081114"
foreground = "#888FA0"

[colors.cursor]
cursor = "#BCB89D"

[colors.normal]
black   = "#353E42"
red     = "#3193B9"
green   = "#958224"
yellow  = "#69328D"
blue    = "#258978"
magenta = "#982949"
cyan    = "#1F346A"
white   = "#888FA0"

[colors.bright]
black   = "#5F6470"
red     = "#41C4F7"
green   = "#C6AD30"
yellow  = "#8C43BC"
blue    = "#188875"
magenta = "#B0294F"
cyan    = "#223B7A"
white   = "#888FA0"