$background = rgb(121214)
$foreground = rgb(DFE9F4)
$color0 = rgb(3C3D3F)
$color1 = rgb(C74973)
$color2 = rgb(C9436E)
$color3 = rgb(6882AA)
$color4 = rgb(6D8AA8)
$color5 = rgb(718EA9)
$color6 = rgb(7A90A8)
$color7 = rgb(C9D7E7)
$color8 = rgb(8C97A2)
$color9 = rgb(F31B63)
$color10 = rgb(F6105A)
$color11 = rgb(759CD6)
$color12 = rgb(91B8E0)
$color13 = rgb(96BEE1)
$color14 = rgb(A3C0E0)
$color15 = rgb(C9D7E7)